# Generated by Django 4.2.3 on 2023-09-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('descripation', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
